<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Unit;

class UnitSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Unit::updateOrCreate([
           'unit_number'=>1,
           'unit_type'=>'type',
           'size'=>'fdd',
           'service_charges_per_sqft'=>'dfd',
           'rent'=>12,
           'deposit'=>123,
           'beds'=>'hgf',
           'baths'=>'hgsf',
           'electricity_no'=>1,
           'municipality_no'=>1,
           'gas_no'=>1,
           'no_of_parkings'=>12,
           'parking_no'=>1,
           'unit_status'=>'fda',
           'compound_no'=>'1',
           'floor'=>'gfd',
           'management_fee_type'=>'hgf',
           'management_fee'=>123,
           'Options'=>'hsgf',
           'marketing_title'=>'hfah',
           'marketing_description'=>'ysasfadkfdy',
           'property_photo'=>'jhh',
           'property_id'=>1
         ]); 
         Unit::updateOrCreate([
            'unit_number'=>2,
            'unit_type'=>'type',
            'size'=>'fdd',
            'service_charges_per_sqft'=>'dfd',
            'rent'=>12,
            'deposit'=>123,
            'beds'=>'hgf',
            'baths'=>'hgsf',
            'electricity_no'=>1,
            'municipality_no'=>1,
            'gas_no'=>1,
            'no_of_parkings'=>12,
            'parking_no'=>1,
            'unit_status'=>'fda',
            'compound_no'=>'1',
            'floor'=>'gfd',
            'management_fee_type'=>'hgf',
            'management_fee'=>123,
            'Options'=>'hsgf',
            'marketing_title'=>'hfah',
            'marketing_description'=>'ysasfadkfdy',
            'property_photo'=>'jhh',
            'property_id'=>1
          ]); 
          Unit::updateOrCreate([
            'unit_number'=>3,
            'unit_type'=>'type',
            'size'=>'fdd',
            'service_charges_per_sqft'=>'dfd',
            'rent'=>12,
            'deposit'=>123,
            'beds'=>'hgf',
            'baths'=>'hgsf',
            'electricity_no'=>1,
            'municipality_no'=>1,
            'gas_no'=>1,
            'no_of_parkings'=>12,
            'parking_no'=>1,
            'unit_status'=>'fda',
            'compound_no'=>'1',
            'floor'=>'gfd',
            'management_fee_type'=>'hgf',
            'management_fee'=>123,
            'Options'=>'hsgf',
            'marketing_title'=>'hfah',
            'marketing_description'=>'ysasfadkfdy',
            'property_photo'=>'jhh',
            'property_id'=>1
          ]); 
          Unit::updateOrCreate([
            'unit_number'=>4,
            'unit_type'=>'type',
            'size'=>'fdd',
            'service_charges_per_sqft'=>'dfd',
            'rent'=>12,
            'deposit'=>123,
            'beds'=>'hgf',
            'baths'=>'hgsf',
            'electricity_no'=>1,
            'municipality_no'=>1,
            'gas_no'=>1,
            'no_of_parkings'=>12,
            'parking_no'=>1,
            'unit_status'=>'fda',
            'compound_no'=>'1',
            'floor'=>'gfd',
            'management_fee_type'=>'hgf',
            'management_fee'=>123,
            'Options'=>'hsgf',
            'marketing_title'=>'hfah',
            'marketing_description'=>'ysasfadkfdy',
            'property_photo'=>'jhh',
            'property_id'=>1
          ]);  
    }
}
